spring.datasource.url=jdbc:postgresql://localhost:5432/orders_db
spring.datasource.username=app_user
spring.datasource.password=app_password

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

spring.jpa.show-sql=true
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

jwt.secret=${JWT_SECRET:cambiar-este-valor-por-una-clave-larga-y-aleatoria-en-produccion}
jwt.expiration-ms=86400000